test: use the same version of wasmtime and adapter (#468)
To avoid errors like:

```
Caused by:
    0: import `wasi:cli/environment@0.2.0-rc-2023-12-05` has the wrong type
    1: instance export `get-arguments` has the wrong type
    2: expected func found nothing
make: *** [Makefile:185: /home/runner/work/wasi-libc/wasi-libc/test/build/functional/argv.wasm.err] Error 1
Error: Process completed with exit code 2.
```

Also, bump them to 17.